import { useMemo, useState } from "react";
import { BadgeDollarSign, Check, Clock3, Copy, Gift, Landmark, Send, Share2, Sparkles, Users } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/providers/trpc";
import { useCurrency } from "@/hooks/useCurrency";

function date(value: string | Date) { return new Date(value).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }); }

export default function ReferralDashboard() {
  const utils = trpc.useUtils();
  const { format } = useCurrency();
  const dashboard = trpc.referral.dashboard.useQuery();
  const [copied, setCopied] = useState(false);
  const [form, setForm] = useState({ promotionChannels: "", audienceSize: "", experience: "", notes: "" });
  const convert = trpc.referral.convertAvailable.useMutation({
    onSuccess: async (result) => { toast.success(`${format(result.amount)} from ${result.count} commission${result.count === 1 ? "" : "s"} added to wallet`); await Promise.all([utils.referral.dashboard.invalidate(), utils.wallet.balance.invalidate()]); },
    onError: (error) => toast.error(error.message),
  });
  const apply = trpc.referral.applyReseller.useMutation({
    onSuccess: async () => { toast.success("Reseller referral application submitted"); await utils.referral.dashboard.invalidate(); },
    onError: (error) => toast.error(error.message),
  });
  const link = useMemo(() => dashboard.data ? `${window.location.origin}/login?ref=${encodeURIComponent(dashboard.data.profile.code)}` : "", [dashboard.data]);
  const copy = async () => { await navigator.clipboard.writeText(link); setCopied(true); toast.success("Referral link copied"); window.setTimeout(() => setCopied(false), 1800); };
  if (dashboard.isLoading) return <div className="grid gap-4 sm:grid-cols-2"><div className="h-36 animate-pulse rounded-2xl bg-white" /><div className="h-36 animate-pulse rounded-2xl bg-white" /></div>;
  if (!dashboard.data) return <div className="rounded-2xl bg-white p-8 text-center text-sm text-[#7c8498]">Referral dashboard could not be loaded.</div>;
  const { profile, settings, stats, commissions, application } = dashboard.data;
  const resellerApproved = profile.resellerStatus === "approved";
  const cards = [
    { label: "Referred users", value: String(stats.referredUsers), icon: Users, tone: "#155cff" },
    { label: "Qualified orders", value: String(stats.commissionedOrders), icon: Gift, tone: "#6d35ff" },
    { label: "Pending", value: format(stats.pending), icon: Clock3, tone: "#d97706" },
    { label: "Available", value: format(stats.available), icon: Landmark, tone: "#0b8f34" },
  ];
  return <div className="space-y-5">
    <section className="overflow-hidden rounded-2xl border border-[#dfe6ff] bg-[#071a3d] text-white shadow-[0_18px_50px_rgba(12,37,104,.16)]">
      <div className="grid gap-6 p-6 sm:p-8 lg:grid-cols-[1fr_auto] lg:items-end">
        <div><span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-xs font-black"><Sparkles className="h-3.5 w-3.5" /> {resellerApproved ? "Approved reseller referral tier" : "Standard referral tier"}</span><h2 className="mt-5 max-w-2xl text-2xl font-black tracking-[-.03em] sm:text-3xl">Share Sasify. Earn from every eligible delivered order.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#c8d7f2]">Your rate is snapshotted when an order qualifies. Commissions remain pending for {settings.holdDays} day{settings.holdDays === 1 ? "" : "s"}, then become available for wallet conversion.</p></div>
        <div className="rounded-2xl border border-white/15 bg-white/10 px-5 py-4 backdrop-blur"><p className="text-[11px] font-black uppercase tracking-[.12em] text-[#a9c2ec]">Current rate</p><p className="mt-1 text-3xl font-black">{resellerApproved ? settings.resellerPercent : settings.userPercent}%</p><p className="mt-1 text-xs text-[#c8d7f2]">of eligible order value</p></div>
      </div>
      <div className="border-t border-white/10 bg-black/10 p-5 sm:px-8"><label className="text-[11px] font-black uppercase tracking-[.1em] text-[#a9c2ec]" htmlFor="referral-link">Your referral link</label><div className="mt-2 flex flex-col gap-2 sm:flex-row"><input id="referral-link" value={link} readOnly className="h-11 min-w-0 flex-1 rounded-xl border border-white/15 bg-white/10 px-4 font-mono text-xs text-white outline-none focus:ring-2 focus:ring-[#7aa8ff]" /><button onClick={copy} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-white px-5 text-sm font-black text-[#0a2455] hover:bg-[#edf4ff]">{copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}{copied ? "Copied" : "Copy link"}</button></div></div>
    </section>

    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(({ label, value, icon: Icon, tone }) => <article key={label} className="rounded-2xl border border-[#dfe6ff] bg-white p-5 shadow-[0_8px_28px_rgba(12,37,104,.05)]"><div className="flex items-center justify-between"><span className="rounded-xl p-2.5" style={{ background: `${tone}12`, color: tone }}><Icon className="h-5 w-5" /></span><span className="text-[10px] font-black uppercase tracking-[.1em] text-[#9aa0b4]">Live</span></div><p className="mt-5 text-2xl font-black text-[#0a1128]">{value}</p><p className="mt-1 text-xs font-bold text-[#7c8498]">{label}</p></article>)}</section>

    <section className="grid gap-5 xl:grid-cols-[minmax(0,1.4fr)_minmax(20rem,.8fr)]">
      <div className="overflow-hidden rounded-2xl border border-[#dfe6ff] bg-white"><div className="flex items-center justify-between border-b border-[#edf1ff] px-5 py-4"><div><h3 className="text-sm font-black text-[#0a1128]">Commission ledger</h3><p className="mt-1 text-xs text-[#7c8498]">Immutable order-linked earnings history</p></div><div className="flex items-center gap-2"><BadgeDollarSign className="h-5 w-5 text-[#155cff]" />{Number(stats.available) > 0 && <button disabled={convert.isPending} onClick={() => convert.mutate()} className="rounded-lg bg-[#155cff] px-3 py-2 text-[11px] font-black text-white disabled:opacity-50">{convert.isPending ? "Converting..." : `Convert ${format(stats.available)}`}</button>}</div></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left"><thead className="bg-[#f8faff] text-[10px] font-black uppercase tracking-[.08em] text-[#7c8498]"><tr><th className="px-5 py-3">Order</th><th className="px-4 py-3">Rate</th><th className="px-4 py-3">Commission</th><th className="px-4 py-3">Status</th><th className="px-5 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-[#edf1ff]">{commissions.length ? commissions.map((row: any) => <tr key={row.id}><td className="px-5 py-4"><p className="text-xs font-black text-[#0a1128]">#{row.sourceId}</p><p className="mt-1 text-[11px] text-[#9aa0b4]">{date(row.createdAt)}</p></td><td className="px-4 py-4 text-xs font-bold text-[#596176]">{row.percentage}%</td><td className="px-4 py-4 text-sm font-black text-[#0a1128]">{format(row.amount)}</td><td className="px-4 py-4"><span className={`rounded-full px-2.5 py-1 text-[10px] font-black uppercase ${row.status === "available" ? "bg-[#e9f8ef] text-[#0b8f34]" : row.status === "pending" ? "bg-[#fff5df] text-[#a56200]" : row.status === "converted" ? "bg-[#eef3ff] text-[#155cff]" : "bg-[#fff0f4] text-[#d11f4a]"}`}>{row.status}</span></td><td className="px-5 py-4 text-right text-[11px] font-bold text-[#7c8498]">{row.status === "available" ? "Ready" : "—"}</td></tr>) : <tr><td colSpan={5} className="px-5 py-14 text-center text-sm text-[#7c8498]">No commissions yet. Share your link to begin.</td></tr>}</tbody></table></div></div>

      <aside className="rounded-2xl border border-[#dfe6ff] bg-white p-5"><div className="flex items-center gap-3"><span className="rounded-xl bg-[#eef3ff] p-2.5 text-[#155cff]"><Share2 className="h-5 w-5" /></span><div><h3 className="text-sm font-black text-[#0a1128]">Reseller referral tier</h3><p className="mt-0.5 text-xs text-[#7c8498]">Earn {settings.resellerPercent}% after approval</p></div></div>
      {resellerApproved ? <div className="mt-5 rounded-xl border border-[#cdebd8] bg-[#f2fbf5] p-4"><p className="text-sm font-black text-[#0b7130]">Approved</p><p className="mt-1 text-xs leading-5 text-[#4c725b]">Your reseller rate is automatically applied to new eligible commissions.</p></div> : application?.status === "pending" ? <div className="mt-5 rounded-xl border border-[#ffe2a8] bg-[#fff9ec] p-4"><p className="text-sm font-black text-[#946000]">Application under review</p><p className="mt-1 text-xs leading-5 text-[#806b3b]">Admin will review your audience, channels, and promotion experience.</p></div> : <form className="mt-5 space-y-3" onSubmit={(event) => { event.preventDefault(); apply.mutate({ promotionChannels: form.promotionChannels, audienceSize: Number(form.audienceSize), experience: form.experience, notes: form.notes || undefined }); }}><label className="block text-xs font-bold text-[#596176]">Promotion channels<input required minLength={3} value={form.promotionChannels} onChange={(e) => setForm({ ...form, promotionChannels: e.target.value })} placeholder="YouTube, community, agency..." className="mt-1.5 h-10 w-full rounded-lg border border-[#dfe6ff] px-3 text-sm outline-none focus:border-[#155cff]" /></label><label className="block text-xs font-bold text-[#596176]">Estimated audience<input required type="number" min="0" value={form.audienceSize} onChange={(e) => setForm({ ...form, audienceSize: e.target.value })} placeholder="2500" className="mt-1.5 h-10 w-full rounded-lg border border-[#dfe6ff] px-3 text-sm outline-none focus:border-[#155cff]" /></label><label className="block text-xs font-bold text-[#596176]">Promotion experience<textarea required minLength={20} rows={4} value={form.experience} onChange={(e) => setForm({ ...form, experience: e.target.value })} placeholder="Describe how you will introduce Sasify to your audience." className="mt-1.5 w-full rounded-lg border border-[#dfe6ff] px-3 py-2 text-sm outline-none focus:border-[#155cff]" /></label><label className="block text-xs font-bold text-[#596176]">Additional note <span className="font-medium text-[#9aa0b4]">(optional)</span><textarea rows={2} value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} className="mt-1.5 w-full rounded-lg border border-[#dfe6ff] px-3 py-2 text-sm outline-none focus:border-[#155cff]" /></label><button disabled={apply.isPending} className="inline-flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-[#0a1128] text-sm font-black text-white disabled:opacity-50"><Send className="h-4 w-4" />{apply.isPending ? "Submitting..." : "Apply as reseller referral"}</button></form>}</aside>
    </section>
  </div>;
}
